package backend_gps;


public enum gm_gps_bbtype_t
{
	GM_GPS_BBTYPE_SEQ,
	GM_GPS_BBTYPE_IF_COND,
	GM_GPS_BBTYPE_WHILE_COND,
	GM_GPS_BBTYPE_BEGIN_VERTEX,
	GM_GPS_BBTYPE_PREPARE1,
	GM_GPS_BBTYPE_PREPARE2,
	GM_GPS_BBTYPE_MERGED_TAIL, // special state, generated by intra-merge
	GM_GPS_BBTYPE_MERGED_IF; // special state, generated by intra-merge

	public int getValue()
	{
		return this.ordinal();
	}

	public static gm_gps_bbtype_t forValue(int value)
	{
		return values()[value];
	}
}